name: "TAPGAPI"
author: Khinenw
version: 0.1.1 beta prerelease
description: "An open-source project of API of RPG minigame [To aru PG]."
main: Khinenw\AruPG\ToAruPG
api: 1.12.0
depend: [XcelUpdater]

permissions:
  toarupg.*:
    description: "The permission for using features."
    default: op
    children:
      toarupg.skill:
        description: "The permission for getting description of skill."
        default: true

      toarupg.isp:
        description: "The permission for investing SP."
        default: true

      toarupg.iap:
        description: "The permission for investing AP."
        default: true

      toarupg.ability:
        description: "The permission for reading current ability."
        default: true

      toarupg.save:
        description: "The permission for saving command sender's data."
        default: true

      toarupg.saveall:
        description: "The permission for saving all of user datas."
        default: op

      toarupg.addtrans:
        description: "The permission for adding translation."
        default: op

      toarupg.loadp:
        description: "Loads invalid player."
        default: true

commands:
  skill:
    description: "Gets description of current holding skill."
    usage: "/skill"
    permission: toarupg.skill

  isp:
    description: "Invests SP to current holding skill."
    usage: "/isp"
    permission: toarupg.isp

  iap:
    description: "Invests AP."
    usage: "/iap [status]"
    permission: toarupg.iap

  ability:
    description: "Gets current status."
    usage: "/ability"
    permission: toarupg.ability

  save:
    description: "Saves user data."
    usage: "/save"
    permission: toarupg.save

  saveall:
    description: "Saves all of user datas."
    usage: "/saveall"
    permission: toarupg.saveall

  addtrans:
    description: "Adds a translation."
    usage: "/addtrans"
    permission: toarupg.addtrans

  loadp:
    description: "Loads invalid player."
    usage: "/loadp"
    permission: toarupg.loadp